tasks:
  - before: |
      npm install --global yarn
      yarn global add commitizen
      yarn run setup
      docker build . --tag empyry:latest

github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - mtxr.sqltools
    - mtxr.sqltools-driver-sqlite
    - ms-azuretools.vscode-docker
