tasks:
    - before: |
          npm install --global yarn
          npm install --global commitizen
          npm install --global sqlite3
          yarn run setup

github:
    prebuilds:
        pullRequestsFromForks: true
        addComment: true

vscode:
    extensions:
        - esbenp.prettier-vscode
        - dbaeumer.vscode-eslint
        - mtxr.sqltools
        - mtxr.sqltools-driver-sqlite
