tasks:
    - before: |
          npm install --global yarn
          yarn global add commitizen
          yarn run setup

github:
    prebuilds:
        pullRequestsFromForks: true
        addComment: true

vscode:
    extensions:
        - 42Crunch.vscode-openapi
        - dbaeumer.vscode-eslint
        - esbenp.prettier-vscode
        - mtxr.sqltools
        - mtxr.sqltools-driver-sqlite
